version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # 외부에서 접근할 수 있는 Kafka 리스너를 설정
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092  # Kafka가 리스닝할 주소를 설정
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181  # Kafka가 사용할 Zookeeper 연결 주소를 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1  # consumer_offsets 토픽의 복제 계수 설정
