server:
  port: 8080

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=first-request, first-request-header2 # key, value 값
#            - AddResponseHeader=first-response, first-response-header2 # key, value 값
            - CustomFilter
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
          filters:
#            - AddRequestHeader=first-request, first-requests-header2 # key, value 값
#            - AddResponseHeader=first-response, first-response-header2 # key, value 값
            - CustomFilter

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
